/**
 * Typst compile service (server-side PDF export).
 *
 * Compiles Typst source (produced by renderTypst.ts) to PDF bytes by spawning
 * the standalone `typst` binary. It layers the operational protections the
 * design review mandates for any export backend:
 *
 *   1. Concurrency queue — at most `maxConcurrent` compiles run at once; the
 *      rest wait, and once `maxQueue` are already waiting new requests are
 *      rejected (TypstQueueFullError -> HTTP 503) so a burst can't exhaust CPU.
 *   2. Per-compile hard timeout — a stuck compile is killed after
 *      `compileTimeoutMs`; the temp directory is always removed in a finally.
 *   3. Sandboxed compile root — typst runs with `--root <tempdir>` so `#include`
 *      / `image()` can only RESOLVE paths under that dir (downloaded,
 *      size-bounded attachment images written by the route). Note `--root`
 *      confines path resolution but does NOT itself refuse to follow a symlink
 *      whose target is outside the root; this build never writes user-named or
 *      symlink files into the root (only server-generated `img_<n>.<ext>` with
 *      downloaded image bytes) and exposes no document-reachable `#read`/
 *      `image()` path argument, so there is no reachable host-path disclosure.
 *      As defense-in-depth the route sniffs image magic bytes before writing.
 *   4. No network — typst has no network fetch; images are pre-downloaded by the
 *      route into the compile root, so a document can never trigger an outbound
 *      request (SSRF is structurally impossible here).
 *
 * There is no long-lived process to recycle: each compile is a short-lived
 * child process that exits when done, so memory is naturally bounded.
 */
import { spawn } from 'node:child_process'
import { mkdtemp, rm, writeFile, readFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { config } from '../config/env.js'

/** Thrown when the wait queue is already full — the route maps this to 503. */
export class TypstQueueFullError extends Error {
  constructor() {
    super('typst export queue is full')
    this.name = 'TypstQueueFullError'
  }
}

/** Thrown when a single compile exceeds the hard timeout. */
export class TypstTimeoutError extends Error {
  constructor() {
    super('typst compile timed out')
    this.name = 'TypstTimeoutError'
  }
}

/** Thrown when the typst binary exits non-zero (bad source / missing font). */
export class TypstCompileError extends Error {
  constructor(message: string) {
    super(message)
    this.name = 'TypstCompileError'
  }
}

// ── concurrency queue ────────────────────────────────────────────────────────────
let active = 0
const waiters: Array<() => void> = []

export function acquireSlot(): Promise<void> {
  if (active < config.typstExport.maxConcurrent) {
    active++
    return Promise.resolve()
  }
  if (waiters.length >= config.typstExport.maxQueue) {
    return Promise.reject(new TypstQueueFullError())
  }
  return new Promise<void>((resolve) => {
    waiters.push(() => {
      active++
      resolve()
    })
  })
}

export function releaseSlot(): void {
  active = Math.max(0, active - 1)
  const next = waiters.shift()
  if (next) next()
}

/** An image to place under the compile root so `image(path)` can read it. */
export interface TypstImageInput {
  /** Relative filename inside the compile root (e.g. "img_0.png"). */
  fileName: string
  /** Raw image bytes (already size-bounded by the caller). */
  bytes: Buffer
}

/**
 * Compile Typst source to a PDF buffer. Writes `main.typ` plus any images into a
 * fresh temp dir, runs `typst compile --root <dir> main.typ out.pdf`, reads the
 * result, and removes the dir. The caller must have acquired a slot first (the
 * route acquires BEFORE preparing input so heavy
 * prep is also gated).
 */
export async function compileTypst(source: string, images: TypstImageInput[] = []): Promise<Buffer> {
  const dir = await mkdtemp(join(tmpdir(), 'typst-export-'))
  try {
    const mainPath = join(dir, 'main.typ')
    const outPath = join(dir, 'out.pdf')
    await writeFile(mainPath, source, 'utf8')
    for (const img of images) {
      // fileName is generated by the route (img_<n>.<ext>), never user text, so
      // it cannot traverse; still, join keeps it inside dir.
      await writeFile(join(dir, img.fileName), img.bytes)
    }

    await runTypst(dir, mainPath, outPath)
    return await readFile(outPath)
  } finally {
    await rm(dir, { recursive: true, force: true }).catch(() => {})
  }
}

/** Spawn the typst binary with a hard timeout; reject on non-zero / timeout. */
function runTypst(root: string, mainPath: string, outPath: string): Promise<void> {
  const bin = config.typstExport.binaryPath || 'typst'
  // Explicit font dir for the embedded OSS CJK faces (Noto Sans/Serif CJK SC).
  // Prepended before the positional source so the CJK families the document maps
  // to resolve deterministically; typst still consults its system font book too,
  // and subset-embeds only the glyphs actually used.
  const fontArgs = config.typstExport.fontPath
    ? ['--font-path', config.typstExport.fontPath]
    : []
  return new Promise<void>((resolve, reject) => {
    const child = spawn(
      bin,
      ['compile', '--root', root, ...fontArgs, '--format', 'pdf', mainPath, outPath],
      { stdio: ['ignore', 'ignore', 'pipe'] },
    )
    let stderr = ''
    let settled = false
    const finish = (fn: () => void) => {
      if (settled) return
      settled = true
      clearTimeout(timer)
      fn()
    }
    const timer = setTimeout(() => {
      child.kill('SIGKILL')
      finish(() => reject(new TypstTimeoutError()))
    }, config.typstExport.compileTimeoutMs)

    child.stderr?.on('data', (d) => {
      // Bound the captured stderr so a runaway warning stream can't grow unbounded.
      if (stderr.length < 8192) stderr += String(d)
    })
    child.on('error', (err) => {
      finish(() => reject(new TypstCompileError(`failed to spawn typst: ${err.message}`)))
    })
    child.on('close', (code) => {
      if (code === 0) finish(() => resolve())
      else finish(() => reject(new TypstCompileError(`typst exited ${code}: ${stderr.trim().slice(0, 500)}`)))
    })
  })
}
